name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: '*'
jobs:
  quality:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x'] #'14.x', 
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build
        
      - name: Action For Semantic Release
      # You may pin to the exact commit or the version.
      # uses: cycjimmy/semantic-release-action@3b88c82b34098e8b51e401c1082c9170b0a3ec3c
        uses: cycjimmy/semantic-release-action@v3.0.0
        with:
          branch: main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
